import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CookieIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1080, 720))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainM = QtWidgets.QWidget()
        self.mainM.setObjectName("mainM")
        self.mainLogo = QtWidgets.QLabel(self.mainM)
        self.mainLogo.setGeometry(QtCore.QRect(340, 157, 400, 90))
        self.mainLogo.setText("")
        self.mainLogo.setPixmap(QtGui.QPixmap("GUIMainLogo.PNG"))
        self.mainLogo.setScaledContents(True)
        self.mainLogo.setObjectName("mainLogo")
        self.userPushButton = QtWidgets.QPushButton(self.mainM)
        self.userPushButton.setGeometry(QtCore.QRect(340, 357, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userPushButton.setFont(font)
        self.userPushButton.setObjectName("userPushButton")
        self.topicPushButton = QtWidgets.QPushButton(self.mainM)
        self.topicPushButton.setGeometry(QtCore.QRect(590, 357, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicPushButton.setFont(font)
        self.topicPushButton.setObjectName("topicPushButton")
        self.stackedWidget.addWidget(self.mainM)
        self.userM = QtWidgets.QWidget()
        self.userM.setObjectName("userM")
        self.userLogo = QtWidgets.QLabel(self.userM)
        self.userLogo.setGeometry(QtCore.QRect(340, 78, 400, 90))
        self.userLogo.setText("")
        self.userLogo.setPixmap(QtGui.QPixmap("GUIMainLogo.PNG"))
        self.userLogo.setScaledContents(True)
        self.userLogo.setObjectName("userLogo")
        self.ytTextBox = QtWidgets.QLineEdit(self.userM)
        self.ytTextBox.setGeometry(QtCore.QRect(140, 178, 800, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ytTextBox.setFont(font)
        self.ytTextBox.setObjectName("ytTextBox")
        self.tTextBox = QtWidgets.QLineEdit(self.userM)
        self.tTextBox.setGeometry(QtCore.QRect(140, 228, 800, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tTextBox.setFont(font)
        self.tTextBox.setObjectName("tTextBox")
        self.ytLabel = QtWidgets.QLabel(self.userM)
        self.ytLabel.setGeometry(QtCore.QRect(65, 178, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ytLabel.setFont(font)
        self.ytLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ytLabel.setObjectName("ytLabel")
        self.tLabel = QtWidgets.QLabel(self.userM)
        self.tLabel.setGeometry(QtCore.QRect(70, 228, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tLabel.setFont(font)
        self.tLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tLabel.setObjectName("tLabel")
        self.userNoteLabel = QtWidgets.QLabel(self.userM)
        self.userNoteLabel.setGeometry(QtCore.QRect(125, 253, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userNoteLabel.setFont(font)
        self.userNoteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userNoteLabel.setObjectName("userNoteLabel")
        self.userCrawlPush = QtWidgets.QPushButton(self.userM)
        self.userCrawlPush.setGeometry(QtCore.QRect(215, 328, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userCrawlPush.setFont(font)
        self.userCrawlPush.setObjectName("userCrawlPush")
        self.userBackPush = QtWidgets.QPushButton(self.userM)
        self.userBackPush.setGeometry(QtCore.QRect(715, 328, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userBackPush.setFont(font)
        self.userBackPush.setObjectName("userBackPush")
        self.stackedWidget.addWidget(self.userM)
        self.topicM = QtWidgets.QWidget()
        self.topicM.setObjectName("topicM")
        self.topicLogo = QtWidgets.QLabel(self.topicM)
        self.topicLogo.setGeometry(QtCore.QRect(340, 78, 400, 90))
        self.topicLogo.setText("")
        self.topicLogo.setPixmap(QtGui.QPixmap("GUIMainLogo.PNG"))
        self.topicLogo.setScaledContents(True)
        self.topicLogo.setObjectName("topicLogo")
        self.topicCrawlPush = QtWidgets.QPushButton(self.topicM)
        self.topicCrawlPush.setGeometry(QtCore.QRect(340, 328, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicCrawlPush.setFont(font)
        self.topicCrawlPush.setObjectName("topicCrawlPush")
        self.topicBackPush = QtWidgets.QPushButton(self.topicM)
        self.topicBackPush.setGeometry(QtCore.QRect(590, 328, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicBackPush.setFont(font)
        self.topicBackPush.setObjectName("topicBackPush")
        self.topicTextBox = QtWidgets.QLineEdit(self.topicM)
        self.topicTextBox.setGeometry(QtCore.QRect(340, 178, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicTextBox.setFont(font)
        self.topicTextBox.setObjectName("topicTextBox")
        self.countryTextBox = QtWidgets.QLineEdit(self.topicM)
        self.countryTextBox.setGeometry(QtCore.QRect(340, 228, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countryTextBox.setFont(font)
        self.countryTextBox.setObjectName("countryTextBox")
        self.topicLabel = QtWidgets.QLabel(self.topicM)
        self.topicLabel.setGeometry(QtCore.QRect(270, 178, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicLabel.setFont(font)
        self.topicLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topicLabel.setObjectName("topicLabel")
        self.countryLabel = QtWidgets.QLabel(self.topicM)
        self.countryLabel.setGeometry(QtCore.QRect(270, 228, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countryLabel.setFont(font)
        self.countryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.countryLabel.setObjectName("countryLabel")
        self.topicNoteLabel = QtWidgets.QLabel(self.topicM)
        self.topicNoteLabel.setGeometry(QtCore.QRect(325, 253, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.topicNoteLabel.setFont(font)
        self.topicNoteLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.topicNoteLabel.setObjectName("topicNoteLabel")
        self.stackedWidget.addWidget(self.topicM)
        self.snsM = QtWidgets.QWidget()
        self.snsM.setObjectName("snsM")
        self.ytLogo = QtWidgets.QLabel(self.snsM)
        self.ytLogo.setGeometry(QtCore.QRect(50, 20, 120, 100))
        self.ytLogo.setText("")
        self.ytLogo.setPixmap(QtGui.QPixmap("YouTubeLogo.png"))
        self.ytLogo.setScaledContents(True)
        self.ytLogo.setObjectName("ytLogo")
        self.tLogo = QtWidgets.QLabel(self.snsM)
        self.tLogo.setGeometry(QtCore.QRect(50, 140, 120, 100))
        self.tLogo.setText("")
        self.tLogo.setPixmap(QtGui.QPixmap("TwitterLogo.png"))
        self.tLogo.setScaledContents(True)
        self.tLogo.setObjectName("label_11")
        self.subCountLabel = QtWidgets.QLabel(self.snsM)
        self.subCountLabel.setGeometry(QtCore.QRect(132, 10, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subCountLabel.setFont(font)
        self.subCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subCountLabel.setObjectName("subCountLabel")
        self.viewCountLabel = QtWidgets.QLabel(self.snsM)
        self.viewCountLabel.setGeometry(QtCore.QRect(158, 35, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewCountLabel.setFont(font)
        self.viewCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.viewCountLabel.setObjectName("viewCountLabel")
        self.videoCountLabel = QtWidgets.QLabel(self.snsM)
        self.videoCountLabel.setGeometry(QtCore.QRect(160, 60, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.videoCountLabel.setFont(font)
        self.videoCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoCountLabel.setObjectName("videoCountLabel")
        self.ytCreatedLabel = QtWidgets.QLabel(self.snsM)
        self.ytCreatedLabel.setGeometry(QtCore.QRect(135, 85, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ytCreatedLabel.setFont(font)
        self.ytCreatedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ytCreatedLabel.setObjectName("ytCreatedLabel")
        self.followerCountLabel = QtWidgets.QLabel(self.snsM)
        self.followerCountLabel.setGeometry(QtCore.QRect(152, 130, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.followerCountLabel.setFont(font)
        self.followerCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.followerCountLabel.setObjectName("followerCountLabel")
        self.tweetsLikedLabel = QtWidgets.QLabel(self.snsM)
        self.tweetsLikedLabel.setGeometry(QtCore.QRect(165, 155, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tweetsLikedLabel.setFont(font)
        self.tweetsLikedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tweetsLikedLabel.setObjectName("tweetsLikedLabel")
        self.totalTweetsLabel = QtWidgets.QLabel(self.snsM)
        self.totalTweetsLabel.setGeometry(QtCore.QRect(145, 180, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalTweetsLabel.setFont(font)
        self.totalTweetsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalTweetsLabel.setObjectName("totalTweetsLabel")
        self.tCreatedLabel = QtWidgets.QLabel(self.snsM)
        self.tCreatedLabel.setGeometry(QtCore.QRect(137, 205, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tCreatedLabel.setFont(font)
        self.tCreatedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tCreatedLabel.setObjectName("tCreatedLabel")
        self.seperateLineLabel = QtWidgets.QLabel(self.snsM)
        self.seperateLineLabel.setGeometry(QtCore.QRect(-20, 210, 1100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.seperateLineLabel.setFont(font)
        self.seperateLineLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.seperateLineLabel.setObjectName("seperateLineLabel")
        self.snsBackPush = QtWidgets.QPushButton(self.snsM)
        self.snsBackPush.setGeometry(QtCore.QRect(920, 580, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.snsBackPush.setFont(font)
        self.snsBackPush.setObjectName("snsBackPush")
        self.stackedWidget.addWidget(self.snsM)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cookie Crawler"))
        self.userPushButton.setText(_translate("MainWindow", "User"))
        self.topicPushButton.setText(_translate("MainWindow", "Topic"))
        self.ytTextBox.setPlaceholderText(_translate("MainWindow", "Enter Youtube Channel URL: E.g., <https://www.youtube.com/channel>"))
        self.tTextBox.setPlaceholderText(_translate("MainWindow", "Enter Twitter User URL: E.g., <https://twitter.com/leehsienloong>"))
        self.ytLabel.setText(_translate("MainWindow", "YouTube:"))
        self.tLabel.setText(_translate("MainWindow", "Twitter:"))
        self.userNoteLabel.setText(_translate("MainWindow", "Note: Leave fields empty for random crawl"))
        self.userCrawlPush.setText(_translate("MainWindow", "Crawl!"))
        self.userBackPush.setText(_translate("MainWindow", "Back"))
        self.topicCrawlPush.setText(_translate("MainWindow", "Crawl!"))
        self.topicBackPush.setText(_translate("MainWindow", "Back"))
        self.topicTextBox.setPlaceholderText(_translate("MainWindow", "Enter Topic:"))
        self.countryTextBox.setPlaceholderText(_translate("MainWindow", "Enter Country"))
        self.topicLabel.setText(_translate("MainWindow", "Topic:"))
        self.countryLabel.setText(_translate("MainWindow", "Country:"))
        self.topicNoteLabel.setText(_translate("MainWindow", "Note: Leave fields empty for random crawl"))
        self.subCountLabel.setText(_translate("MainWindow", "Sub Count:"))
        self.viewCountLabel.setText(_translate("MainWindow", "Total View Count:"))
        self.videoCountLabel.setText(_translate("MainWindow", "Total Video Count:"))
        self.ytCreatedLabel.setText(_translate("MainWindow", "Created At:"))
        self.followerCountLabel.setText(_translate("MainWindow", "Follower Count:"))
        self.tweetsLikedLabel.setText(_translate("MainWindow", "Total Tweets Liked:"))
        self.totalTweetsLabel.setText(_translate("MainWindow", "Total Tweets:"))
        self.tCreatedLabel.setText(_translate("MainWindow", "Created At:"))
        self.seperateLineLabel.setText(_translate("MainWindow", "____________________________________________________________________________"))
        self.snsBackPush.setText(_translate("MainWindow", "Back"))


# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())
